### PR TITLE
Comment-out usage of an undefined variable

### PR DESCRIPTION
**Pull request by boris-petrov**
Until someone figures out how to import the CSS correctly

### CODE REVIEW

**Comment by boris-petrov** [comment]
Ping @vandernorth. :)

**Comment by vandernorth** [comment]
Sorry this took more than 2 years ;-)

**Comment by boris-petrov** [comment]
No worries. :)

**Comment by boris-petrov** [comment]
@vandernorth - I see you released a new version but without the changes in this PR. :) Mind releasing an even newer one with them? :)

**Comment by vandernorth** [comment]
yeah let's not wait another 2 years for that. 0.7.4 has just been released.

**Pull request merged**
